[megatron] fix: patched_routing accepts arbitrary args
Introduced from https://github.com/NVIDIA/Megatron-LM/commit/71c49b56da0c9d2d4fa32a2ac11bde5bd01261c9

```logs
  File "megatron/core/transformer/moe/moe_layer.py", line 448, in forward
    outputs = custom_forward(hidden_states, intermediate_tensors, padding_mask)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "megatron/core/transformer/moe/moe_layer.py", line 393, in custom_forward
    probs, routing_map = self.route(hidden_states, padding_mask)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "megatron/core/transformer/moe/moe_utils.py", line 1472, in wrapped_func
    return func(moe_layer, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "megatron/core/transformer/moe/moe_layer.py", line 252, in route
    probs, routing_map = apply_module(self.router)(hidden_states, padding_mask)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "megatron/core/transformer/moe/router.py", line 659, in forward
    probs, routing_map = self.routing(logits, padding_mask=padding_mask)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: patched_routing() got an unexpected keyword argument 'padding_mask'
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>